require "user.options"
require "user.modeconfig"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"
require "user.cmp"
require "user.lsp"
require "user.telescope"
require "user.treesitter"
require "user.autopairs"
require "user.comment"
require "user.gitsigns"
require "user.nvim-tree"
require "user.bufferline"
require "user.lualine"
require "user.toggleterm"
require "user.dap"
require "user.dashboard"
require "user.nvim-scrollbar"
require "user.todo-comments"
require "user.notification"
require "user.symbols_outline"
-- require "user.orgmode"
-- require "user.fold"
require "user.latex"
require "user.indent-blankline"
require "user.treesitter-context"
