#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa
yabai -m config debug_output on

source $HOME/.config/yabai/color.sh

# Signal
yabai -m signal --add event=space_changed \
    action="sh $HOME/.config/yabai/keep_color.sh"

# layout
yabai -m config layout bsp
yabai -m config --space 6 layout float
yabai -m config window_placement second_child


# Window Opacity
yabai -m config active_window_opacity   1.00
yabai -m config normal_window_opacity   1.00
yabai -m config window_opacity          on


# Padding
yabai -m config top_padding    1
yabai -m config bottom_padding 1
yabai -m config left_padding   3
yabai -m config right_padding  3
yabai -m config window_gap     5


# Border
yabai -m config window_border               on
yabai -m config window_border_width         2
yabai -m config window_border_radius        10
yabai -m config active_window_border_color  $bsp_border_color 
yabai -m config normal_window_border_color  $normal_border_color 
yabai -m config window_border_hidpi         on
yabai -m config window_border               on
yabai -m config window_border_blur          off


# Mouse
yabai -m config mouse_modifier  alt
yabai -m config mouse_action1   move
yabai -m config mouse_action2   resize
yabai -m config mouse_follows_focus on


# Space Label
yabai -m space 1 --label "Safari"
yabai -m space 2 --label "Terminal"
yabai -m space 3 --label "Reading"
yabai -m space 4 --label "Note"
yabai -m space 5 --label "Other"
yabai -m space 6 --label "Game"


# Rules
yabai -m rule --add app="System Settings"   manage=off
yabai -m rule --add app="Finder"            manage=off
yabai -m rule --add app="Font Book"         manage=off
yabai -m rule --add app="BaiduNetdisk"      manage=off
yabai -m rule --add app="FileZilla"         manage=off
yabai -m rule --add app="Raycast"           manage=off
yabai -m rule --add app="Dash"              manage=off
yabai -m rule --add app="Shottr"            manage=off
yabai -m rule --add app="ClashX Pro"        manage=off
yabai -m rule --add app="EuDic"             manage=off border=off
yabai -m rule --add app="Calculator"        manage=off border=off
yabai -m rule --add app="Numi"              manage=off border=off grid=4:4:1:1:2:2

yabai -m rule --add app="Orion" title="General" manage=off
yabai -m rule --add app="Orion" title="Extension" manage=off

yabai -m rule --add app="WeChat"            manage=off space=^6 grid=4:4:1:1:2:2
yabai -m rule --add app="QQ"                manage=off space=^6
yabai -m rule --add app="Telegram"          manage=off space=^6

yabai -m rule --add app="Safari"            space=^1
yabai -m rule --add app="Orion"             space=^1
yabai -m rule --add app="Chrome"            space=^1
yabai -m rule --add app="iterm2"            space=^2
yabai -m rule --add app="PDF Expert"        space=^3
yabai -m rule --add app="Obsidian"          space=^4
# yabai -m rule --add app="kitty"             opacity=0.9

# Other
yabai -m config auto_balance off
